export const FATCH_USERS_REQUEST = 'FATCH_USERS_REQUEST'
export const FATCH_USERS_SUCCESS = 'FATCH_USERS_SUCCESS'
export const FATCH_USERS_FAILURE = 'FATCH_USERS_FAILURE'

export const INCREMENT_PAGE = "INCREMENT_PAGE"
export const ADD_MOVIE_TO_REDUX = "ADD_MOVIE_TO_REDUX"